// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class CollectionExtensionsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::CollectionExtensionsTest))]
public void AddRanges132()
{
    int[] ints = new int[1];
    this.AddRanges(ints, 1, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CollectionExtensionsTest))]
public void AddRanges822()
{
    int[] ints = new int[1];
    this.AddRanges(ints, 0, 1);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CollectionExtensionsTest))]
public void AddRanges348()
{
    int[] ints = new int[3];
    ints[0] = 32;
    ints[2] = 1;
    this.AddRanges(ints, 2, 1);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CollectionExtensionsTest))]
public void AddRanges571()
{
    int[] ints = new int[3];
    ints[0] = 4;
    ints[2] = 1;
    this.AddRanges(ints, 0, 3);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CollectionExtensionsTest))]
public void AddRanges72()
{
    int[] ints = new int[6];
    ints[1] = 2;
    ints[2] = 9;
    ints[3] = 513;
    ints[4] = 64;
    ints[5] = 1;
    this.AddRanges(ints, 1, 5);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CollectionExtensionsTest))]
public void AddRanges75()
{
    int[] ints = new int[4];
    ints[1] = 3;
    ints[2] = 2;
    ints[3] = 1;
    this.AddRanges(ints, 0, 4);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CollectionExtensionsTest))]
public void AddRanges694()
{
    int[] ints = new int[9];
    ints[1] = 9;
    ints[2] = 257;
    ints[3] = 65;
    ints[4] = 3;
    ints[5] = 1;
    ints[6] = 520;
    ints[7] = 512;
    ints[8] = 513;
    this.AddRanges(ints, 0, 9);
}
}
