// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System.Configuration.Assemblies;

public partial class CommonUtilsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::CommonUtilsTest))]
public void CloneT18801()
{
    ICloneable iCloneable;
    object box = (object)(default(AssemblyHash));
    iCloneable = this.CloneT<ICloneable>((ICloneable)box);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CommonUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CloneTThrowsArgumentNullException342()
{
    ICloneable iCloneable;
    iCloneable = this.CloneT<ICloneable>((ICloneable)null);
}
}
