// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class CommonUtilsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::CommonUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TryNullReference01ThrowsArgumentNullException527()
{
    int i;
    i = this.TryNullReference01<int>((Func<int>)null, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CommonUtilsTest))]
public void TryNullReference01462()
{
    object o;
    int i;
    o = FuncFactory.Create(false, false, 0);
    i = this.TryNullReference01<int>((Func<int>)o, 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CommonUtilsTest))]
[ExpectedException(typeof(OperationCanceledException))]
public void TryNullReference01ThrowsOperationCanceledException31()
{
    object o;
    int i;
    o = FuncFactory.Create(true, false, 0);
    i = this.TryNullReference01<int>((Func<int>)o, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CommonUtilsTest))]
public void TryNullReference0146201()
{
    object o;
    int i;
    o = FuncFactory.Create(true, true, 0);
    i = this.TryNullReference01<int>((Func<int>)o, 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CommonUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TryNullReferenceThrowsArgumentNullException467()
{
    int i;
    i = this.TryNullReference<int>((Func<int>)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CommonUtilsTest))]
public void TryNullReference817()
{
    object o;
    int i;
    o = FuncFactory.Create(false, false, 0);
    i = this.TryNullReference<int>((Func<int>)o);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CommonUtilsTest))]
[ExpectedException(typeof(OperationCanceledException))]
public void TryNullReferenceThrowsOperationCanceledException295()
{
    object o;
    int i;
    o = FuncFactory.Create(true, false, 0);
    i = this.TryNullReference<int>((Func<int>)o);
}
[TestMethod]
[PexGeneratedBy(typeof(global::CommonUtilsTest))]
public void TryNullReference81701()
{
    object o;
    int i;
    o = FuncFactory.Create(true, true, 0);
    i = this.TryNullReference<int>((Func<int>)o);
    Assert.AreEqual<int>(0, i);
}
}
