// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class DateTimeUtilsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::DateTimeUtilsTest))]
public void CalculateAge01392()
{
    int i;
    i = this.CalculateAge01(default(DateTime), default(DateTime));
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::DateTimeUtilsTest))]
public void CalculateAge01181()
{
    int i;
    i = this.CalculateAge01(new DateTime(4611686018427387903L & 2285646977695745L, 
                                         (DateTimeKind)(2285646977695745uL >> 62)), 
                            new DateTime(4611686018427387903L & 2272099842869428224L, 
                                         (DateTimeKind)(2272099842869428224uL >> 62)));
    Assert.AreEqual<int>(7192, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::DateTimeUtilsTest))]
public void CalculateAge01255()
{
    int i;
    i = this.CalculateAge01(new DateTime(4611686018427387903L & 885320149106689L, 
                                         (DateTimeKind)(885320149106689uL >> 62)), 
                            new DateTime(4611686018427387903L & 946272143933440L, 
                                         (DateTimeKind)(946272143933440uL >> 62)));
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::DateTimeUtilsTest))]
[ExpectedException(typeof(ArgumentException))]
public void CalculateAge01ThrowsArgumentException745()
{
    int i;
    i = this.CalculateAge01
            (new DateTime(4611686018427387903L & 1L, (DateTimeKind)(1uL >> 62)), 
             default(DateTime));
}
}
