// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class GenericEnumerableExtensionsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void Concat01ThrowsArgumentNullException551()
{
    IEnumerable<int> iEnumerable;
    iEnumerable = this.Concat01<int>((IEnumerable<int>)null, (int[])null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void Concat01ThrowsArgumentNullException424()
{
    IEnumerable<int> iEnumerable;
    int[] ints = new int[0];
    iEnumerable = this.Concat01<int>((IEnumerable<int>)ints, (int[])null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void Concat01403()
{
    IEnumerable<int> iEnumerable;
    int[] ints = new int[0];
    int[] ints1 = new int[0];
    iEnumerable = this.Concat01<int>((IEnumerable<int>)ints, ints1);
    Assert.IsNotNull((object)iEnumerable);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void Concat923()
{
    IEnumerable<int> iEnumerable;
    iEnumerable = this.Concat<int>((IEnumerable<int>)null, 0);
    Assert.IsNotNull((object)iEnumerable);
}
}
