// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class GenericEnumerableExtensionsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void RandomThrowsArgumentNullException376()
{
    int i;
    i = this.Random<int>((IEnumerable<int>)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void RandomThrowsInvalidOperationException726()
{
    int i;
    int[] ints = new int[0];
    i = this.Random<int>((IEnumerable<int>)ints);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void Random348()
{
    int i;
    int[] ints = new int[1];
    i = this.Random<int>((IEnumerable<int>)ints);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void Random446()
{
    int i;
    int[] ints = new int[2];
    i = this.Random<int>((IEnumerable<int>)ints);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void Random876()
{
    int i;
    int[] ints = new int[4];
    i = this.Random<int>((IEnumerable<int>)ints);
    Assert.AreEqual<int>(0, i);
}
}
