// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class GenericEnumerableExtensionsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ForEachThrowsArgumentNullException437()
{
    this.ForEach<int>((IEnumerable<int>)null, (Action<int>)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ForEachThrowsArgumentNullException434()
{
    int[] ints = new int[0];
    this.ForEach<int>((IEnumerable<int>)ints, (Action<int>)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void ForEach9()
{
    object o;
    o = ActionFactory.Create();
    int[] ints = new int[0];
    this.ForEach<int>((IEnumerable<int>)ints, (Action<int>)o);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void ForEach217()
{
    object o;
    o = ActionFactory.Create();
    int[] ints = new int[1];
    this.ForEach<int>((IEnumerable<int>)ints, (Action<int>)o);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void ForEach915()
{
    object o;
    o = ActionFactory.Create();
    int[] ints = new int[2];
    this.ForEach<int>((IEnumerable<int>)ints, (Action<int>)o);
}
}
