// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class GenericEnumerableExtensionsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CountThrowsArgumentNullException838()
{
    int i;
    i = this.Count<int>((IEnumerable<int>)null, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void Count312()
{
    int i;
    int[] ints = new int[0];
    i = this.Count<int>((IEnumerable<int>)ints, 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void Count260()
{
    int i;
    int[] ints = new int[1];
    i = this.Count<int>((IEnumerable<int>)ints, 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void Count537()
{
    int i;
    int[] ints = new int[1];
    ints[0] = 1;
    i = this.Count<int>((IEnumerable<int>)ints, 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void Count222()
{
    int i;
    int[] ints = new int[2];
    i = this.Count<int>((IEnumerable<int>)ints, 0);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::GenericEnumerableExtensionsTest))]
public void Count955()
{
    int i;
    int[] ints = new int[3];
    ints[0] = 1;
    i = this.Count<int>((IEnumerable<int>)ints, 1);
    Assert.AreEqual<int>(1, i);
}
}
