// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class MathExTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime01671()
{
    bool b;
    b = this.IsPrime01((short)32);
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime01797()
{
    bool b;
    b = this.IsPrime01((short)125);
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime01578()
{
    bool b;
    b = this.IsPrime01((short)0);
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime01139()
{
    bool b;
    b = this.IsPrime01((short)2);
    Assert.AreEqual<bool>(true, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime01674()
{
    bool b;
    b = this.IsPrime01((short)23);
    Assert.AreEqual<bool>(true, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime01101()
{
    bool b;
    b = this.IsPrime01((short)43);
    Assert.AreEqual<bool>(true, b);
}
}
