// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class MathExTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Min03581()
{
    double d;
    double[] ds = new double[1];
    d = this.Min03(ds);
    Assert.AreEqual<double>(0, d);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Min03304()
{
    double d;
    double[] ds = new double[2];
    ds[0] = 2438;
    ds[1] = 2437;
    d = this.Min03(ds);
    Assert.AreEqual<double>(2437, d);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Min03687()
{
    double d;
    double[] ds = new double[2];
    ds[0] = 7059;
    ds[1] = 8855;
    d = this.Min03(ds);
    Assert.AreEqual<double>(7059, d);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Min03670()
{
    double d;
    double[] ds = new double[3];
    ds[0] = double.PositiveInfinity;
    ds[1] = 7059;
    ds[2] = double.NaN;
    d = this.Min03(ds);
    Assert.AreEqual<double>(double.NaN, d);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void Min03ThrowsArgumentNullException190()
{
    double d;
    d = this.Min03((double[])null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void Min03ThrowsInvalidOperationException911()
{
    double d;
    double[] ds = new double[0];
    d = this.Min03(ds);
}
}
