// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class MathExTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Min01581()
{
    short w;
    short[] ws = new short[1];
    w = this.Min01(ws);
    Assert.AreEqual<short>((short)0, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Min01205()
{
    short w;
    short[] ws = new short[2];
    ws[0] = (short)59;
    ws[1] = (short)64;
    w = this.Min01(ws);
    Assert.AreEqual<short>((short)59, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Min01695()
{
    short w;
    short[] ws = new short[2];
    ws[0] = (short)83;
    ws[1] = (short)34;
    w = this.Min01(ws);
    Assert.AreEqual<short>((short)34, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void Min01ThrowsArgumentNullException442()
{
    short w;
    w = this.Min01((short[])null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void Min01ThrowsInvalidOperationException83()
{
    short w;
    short[] ws = new short[0];
    w = this.Min01(ws);
}
}
