// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class MathExTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime02671()
{
    bool b;
    b = this.IsPrime02((ushort)32);
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime02285()
{
    bool b;
    b = this.IsPrime02((ushort)35);
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime02578()
{
    bool b;
    b = this.IsPrime02((ushort)0);
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime02258()
{
    bool b;
    b = this.IsPrime02((ushort)3);
    Assert.AreEqual<bool>(true, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime02139()
{
    bool b;
    b = this.IsPrime02((ushort)2);
    Assert.AreEqual<bool>(true, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void IsPrime02349()
{
    bool b;
    b = this.IsPrime02((ushort)97);
    Assert.AreEqual<bool>(true, b);
}
}
