// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class MathExTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Max02581()
{
    ushort w;
    ushort[] ws = new ushort[1];
    w = this.Max02(ws);
    Assert.AreEqual<ushort>((ushort)0, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Max02690()
{
    ushort w;
    ushort[] ws = new ushort[2];
    ws[0] = (ushort)92;
    ws[1] = (ushort)92;
    w = this.Max02(ws);
    Assert.AreEqual<ushort>((ushort)92, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Max02655()
{
    ushort w;
    ushort[] ws = new ushort[2];
    ws[0] = (ushort)66;
    ws[1] = (ushort)105;
    w = this.Max02(ws);
    Assert.AreEqual<ushort>((ushort)105, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void Max02ThrowsArgumentNullException511()
{
    ushort w;
    w = this.Max02((ushort[])null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void Max02ThrowsInvalidOperationException583()
{
    ushort w;
    ushort[] ws = new ushort[0];
    w = this.Max02(ws);
}
}
