// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class MathExTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Abs02284()
{
    double d;
    d = this.Abs02(0);
    Assert.AreEqual<double>(0, d);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Abs02726()
{
    double d;
    d = this.Abs02(-1);
    Assert.AreEqual<double>(1, d);
}
}
