// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class MathExTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Max03581()
{
    double d;
    double[] ds = new double[1];
    d = this.Max03(ds);
    Assert.AreEqual<double>(0, d);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Max03743()
{
    double d;
    double[] ds = new double[2];
    ds[0] = 2437;
    ds[1] = 2438;
    d = this.Max03(ds);
    Assert.AreEqual<double>(2438, d);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Max03872()
{
    double d;
    double[] ds = new double[2];
    ds[0] = 8855;
    ds[1] = 7059;
    d = this.Max03(ds);
    Assert.AreEqual<double>(8855, d);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void Max03ThrowsArgumentNullException98()
{
    double d;
    d = this.Max03((double[])null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void Max03ThrowsInvalidOperationException12()
{
    double d;
    double[] ds = new double[0];
    d = this.Max03(ds);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Max03846()
{
    double d;
    double[] ds = new double[2];
    ds[0] = double.NaN;
    ds[1] = 9.8813129168249309E-324;
    d = this.Max03(ds);
    Assert.AreEqual<double>(9.8813129168249309E-324, d);
}
}
