// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class MathExTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Abs03284()
{
    decimal d;
    d = this.Abs03(default(decimal));
    Assert.AreEqual<decimal>(default(decimal), d);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Abs03898()
{
    decimal d;
    d = this.Abs03(-76819052936496198642298613574e-19M);
    Assert.AreEqual<decimal>(76819052936496198642298613574e-19M, d);
}
}
