// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Exceptions;

public partial class MathExTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Gcd01833()
{
    short w;
    w = this.Gcd01((short)32, (short)32);
    Assert.AreEqual<short>((short)32, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Gcd01972()
{
    short w;
    w = this.Gcd01((short)0, (short)32);
    Assert.AreEqual<short>((short)32, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Gcd01509()
{
    short w;
    w = this.Gcd01((short)32, (short)0);
    Assert.AreEqual<short>((short)32, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(OverflowException))]
public void Gcd01ThrowsOverflowException477()
{
    short w;
    w = this.Gcd01((short)short.MinValue, (short)32);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Gcd01835()
{
    short w;
    w = this.Gcd01((short)122, (short)62);
    Assert.AreEqual<short>((short)2, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Gcd01130()
{
    short w;
    w = this.Gcd01((short)(-1), (short)32);
    Assert.AreEqual<short>((short)1, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(OverflowException))]
public void Gcd01ThrowsOverflowException734()
{
    short w;
    w = this.Gcd01((short)(-1), (short)short.MinValue);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void Gcd01ThrowsInvalidOperationException904()
{
    short w;
    w = this.Gcd01((short)0, (short)0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Gcd01288()
{
    short w;
    w = this.Gcd01((short)32, (short)(-1));
    Assert.AreEqual<short>((short)1, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Gcd01703()
{
    short w;
    w = this.Gcd01((short)0, (short)(-1));
    Assert.AreEqual<short>((short)1, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Gcd01587()
{
    short w;
    w = this.Gcd01((short)(-1), (short)(-1));
    Assert.AreEqual<short>((short)1, w);
}
}
