// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class MathExTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Min02581()
{
    ushort w;
    ushort[] ws = new ushort[1];
    w = this.Min02(ws);
    Assert.AreEqual<ushort>((ushort)0, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Min02344()
{
    ushort w;
    ushort[] ws = new ushort[2];
    ws[0] = (ushort)79;
    ws[1] = (ushort)80;
    w = this.Min02(ws);
    Assert.AreEqual<ushort>((ushort)79, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
public void Min02851()
{
    ushort w;
    ushort[] ws = new ushort[2];
    ws[0] = (ushort)84;
    ws[1] = (ushort)64;
    w = this.Min02(ws);
    Assert.AreEqual<ushort>((ushort)64, w);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void Min02ThrowsArgumentNullException871()
{
    ushort w;
    w = this.Min02((ushort[])null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::MathExTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void Min02ThrowsInvalidOperationException380()
{
    ushort w;
    ushort[] ws = new ushort[0];
    w = this.Min02(ws);
}
}
