// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Exceptions;

public partial class StringUtilsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatNamed998()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed((string)null, (string)null);
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{a}", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{0}", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatNamed348()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed((string)null, "");
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{a}", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{0}", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatNamed93()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed((string)null, "\0");
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{a}\0", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{0}\0", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void FormatNamedThrowsPexAssertFailedException151()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed((string)null, "{");
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{a}{", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{0}{", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatNamed825()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("", (string)null);
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{a}", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{0}", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatNamed689()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("{", (string)null);
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{{a}", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{{0}", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatNamed917()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("{", "{");
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{{a}{", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{{0}{", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatNamed72()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("{\0", (string)null);
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{\0{a}", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{\0{0}", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatNamed2()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("{,", (string)null);
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{,{a}", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{,{0}", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void FormatNamedThrowsPexAssertFailedException492()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("{}", (string)null);
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{}{a}", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{}{0}", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatNamed955()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("{:", (string)null);
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{:{a}", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{:{0}", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void FormatNamedThrowsPexAssertFailedException244()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("{", "}");
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{{a}}", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{{0}}", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void FormatNamedThrowsPexAssertFailedException341()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("{{", "{{");
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{{{a}{{", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{{{0}{{", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void FormatNamedThrowsPexAssertFailedException847()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("{}", "{\0");
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{}{a}{\0", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{}{0}{\0", ovformat);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void FormatNamedThrowsPexAssertFailedException355()
{
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      global::StringUtilsTest.FormatNamed("{}", "{{");
      string ovformatNamed = observer.GetObservedValue<string>("formatNamed");
      Assert.AreEqual<string>("{}{a}{{", ovformatNamed);
      string ovformat = observer.GetObservedValue<string>("format");
      Assert.AreEqual<string>("{}{0}{{", ovformat);
    }
}
}
