// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class StringUtilsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(InvalidOperationException))]
public void GetBetweenThrowsInvalidOperationException819()
{
    string s;
    s = this.GetBetween("", "\0", "");
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(InvalidOperationException))]
public void GetBetweenThrowsInvalidOperationException411()
{
    string s;
    s = this.GetBetween("\u0001\0", "\u0001", "\u4000");
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void GetBetweenThrowsArgumentOutOfRangeException579()
{
    string s;
    s = this.GetBetween("", "\0", "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void GetBetween40701()
{
    string s;
    s = this.GetBetween("", "\0\0", "");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void GetBetween14101()
{
    string s;
    s = this.GetBetween("", "", "");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void GetBetween31901()
{
    string s;
    s = this.GetBetween("", "\0\0\0", "\0\0");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void GetBetween58001()
{
    string s;
    s = this.GetBetween("\0", "\0", "\0");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetBetweenThrowsArgumentNullException712()
{
    string s;
    s = this.GetBetween((string)null, (string)null, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetBetweenThrowsArgumentNullException743()
{
    string s;
    s = this.GetBetween("", "", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetBetweenThrowsArgumentNullException849()
{
    string s;
    s = this.GetBetween("", (string)null, (string)null);
}
}
