// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class StringUtilsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatWith566()
{
    this.FormatWith((string)null, (object[])null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatWith817()
{
    this.FormatWith("", (object[])null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void FormatWith337()
{
    object[] os = new object[0];
    this.FormatWith("", os);
}
}
