// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class StringUtilsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetBetweenThrowsArgumentNullException471()
{
    string s;
    s = this.GetBetween((string)null, (string)null, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetBetweenThrowsArgumentNullException27()
{
    string s;
    s = this.GetBetween("", (string)null, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetBetweenThrowsArgumentNullException344()
{
    string s;
    s = this.GetBetween("", "", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void GetBetween141()
{
    string s;
    s = this.GetBetween("", "", "");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(InvalidOperationException))]
public void GetBetweenThrowsInvalidOperationException63()
{
    string s;
    s = this.GetBetween("", "\0\0", "\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(InvalidOperationException))]
public void GetBetweenThrowsInvalidOperationException490()
{
    string s;
    s = this.GetBetween("", "\0", "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(InvalidOperationException))]
public void GetBetweenThrowsInvalidOperationException944()
{
    string s;
    s = this.GetBetween("\0", "\0", "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[PexRaisedException(typeof(InvalidOperationException))]
public void GetBetweenThrowsInvalidOperationException174()
{
    string s;
    s = this.GetBetween("@\0\u0800", "\0", "\0");
}
}
