// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class StringUtilsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CountThrowsArgumentNullException221()
{
    int i;
    i = this.Count((string)null, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CountThrowsArgumentNullException996()
{
    int i;
    i = this.Count((string)null, "");
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CountThrowsArgumentNullException989()
{
    int i;
    i = this.Count((string)null, "0");
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CountThrowsArgumentNullException637()
{
    int i;
    i = this.Count("", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CountThrowsArgumentNullException145()
{
    int i;
    i = this.Count("0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentException))]
public void CountThrowsArgumentException755()
{
    int i;
    i = this.Count("", "");
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void Count421()
{
    int i;
    i = this.Count("1", "0");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void Count720()
{
    int i;
    i = this.Count("0", "0");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CountThrowsArgumentNullException138()
{
    int i;
    i = this.Count("00", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void Count361()
{
    int i;
    i = this.Count("0", "00");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void Count937()
{
    int i;
    i = this.Count("00", "00");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void Count337()
{
    int i;
    i = this.Count("00", "0");
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void Count744()
{
    int i;
    i = this.Count("000", "000");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void Count351()
{
    int i;
    i = this.Count("0100000", "0100");
    Assert.AreEqual<int>(1, i);
}
}
