// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class StringUtilsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ReplaceThrowsArgumentNullException196()
{
    string s;
    s = this.Replace((string)null, 0, ' ');
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentOutOfRangeException))]
public void ReplaceThrowsArgumentOutOfRangeException248()
{
    string s;
    s = this.Replace("", 0, ' ');
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void Replace725()
{
    string s;
    s = this.Replace("\0", 0, ' ');
    Assert.AreEqual<string>(" ", s);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void Replace457()
{
    string s;
    s = this.Replace("\t", 0, ' ');
    Assert.AreEqual<string>(" ", s);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
public void Replace495()
{
    string s;
    s = this.Replace("\u0100", 0, '\u0100');
    Assert.AreEqual<string>("\u0100", s);
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentOutOfRangeException))]
public void ReplaceThrowsArgumentOutOfRangeException507()
{
    string s;
    s = this.Replace("", 1, ' ');
}
[TestMethod]
[PexGeneratedBy(typeof(global::StringUtilsTest))]
[ExpectedException(typeof(ArgumentOutOfRangeException))]
public void ReplaceThrowsArgumentOutOfRangeException419()
{
    string s;
    s = this.Replace("", int.MinValue, ' ');
}
}
