// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class XmlUtilsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid167()
{
    bool b;
    b = this.CheckValid("\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid267()
{
    bool b;
    b = this.CheckValid("<");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid463()
{
    bool b;
    b = this.CheckValid("&");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid833()
{
    bool b;
    b = this.CheckValid("\u0001");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid641()
{
    bool b;
    b = this.CheckValid("\t");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void CheckValidThrowsNullReferenceException574()
{
    bool b;
    b = this.CheckValid((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid770()
{
    bool b;
    b = this.CheckValid("\n");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid449()
{
    bool b;
    b = this.CheckValid("\ud800\u0001");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid159()
{
    bool b;
    b = this.CheckValid("<\0\0\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid494()
{
    bool b;
    b = this.CheckValid("<?\0\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid639()
{
    bool b;
    b = this.CheckValid("<!\0\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid692()
{
    bool b;
    b = this.CheckValid("<!-\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid706()
{
    bool b;
    b = this.CheckValid("<!--");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid753()
{
    bool b;
    b = this.CheckValid("\0\0\0\0\0\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid570()
{
    bool b;
    b = this.CheckValid("<?x\0\0\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid166()
{
    bool b;
    b = this.CheckValid("<?x?>\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid697()
{
    bool b;
    b = this.CheckValid("<?xml\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid83()
{
    bool b;
    b = this.CheckValid("<?xm \0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid137()
{
    bool b;
    b = this.CheckValid("<?\ub7ce\0\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(global::XmlUtilsTest))]
public void CheckValid352()
{
    bool b;
    b = this.CheckValid("<?xml?\0");
    Assert.AreEqual<bool>(false, b);
}
}
